fix TypeError: get_running_list() missing 1 required positional argument: 'self'  Traceback (most recent call last): 2019-08-09T10:14:44.202705403Z   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app 2019-08-09T10:14:44.202720905Z     response = self.full_dispatch_request() 2019-08-09T10:14:44.202724488Z   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request 2019-08-09T10:14:44.202728155Z     rv = self.handle_user_exception(e) 2019-08-09T10:14:44.202731523Z   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception 2019-08-09T10:14:44.202735074Z     reraise(exc_type, exc_value, tb) 2019-08-09T10:14:44.202738349Z   File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise 2019-08-09T10:14:44.202741803Z     raise value 2019-08-09T10:14:44.202745102Z   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request 2019-08-09T10:14:44.202748626Z     rv = self.dispatch_request() 2019-08-09T10:14:44.202799250Z   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request 2019-08-09T10:14:44.202803427Z     return self.view_functions[rule.endpoint](**req.view_args) 2019-08-09T10:14:44.202806849Z   File "app.py", line 10, in index 2019-08-09T10:14:44.202810220Z     return render_vm_list() 2019-08-09T10:14:44.202813648Z   File "app.py", line 20, in render_vm_list 2019-08-09T10:14:44.202817010Z     vms = activity.get_running_list() 2019-08-09T10:14:44.202820256Z   File "/app/manager/activity.py", line 27, in get_running_list 2019-08-09T10:14:44.202823908Z     return AWS.get_running_list() 2019-08-09T10:14:44.202827181Z TypeError: get_running_list() missing 1 required positional argument: 'self'